### ISSUE TITLE
Change News and Articles (What I'm watching) in the CMS

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/sophiamcclennen.com#12]
Articles are lumped with News. Perhaps we should separate them - previously had just been a category.

In the CMS, at least, they should be separate.

Also
- [ ] allow sorting by date (for both)
- [x] show image in articles

**Comment by regisphilibert** [comment]
@budparr most of those mds have no dates. Now Hugo can use the date found in the pathname but NetlifyCMS cannot.

**Comment by budparr** [comment]
Okay. I think we have the option there and dates for the future. Will non-dated items just show up last?

**Comment by regisphilibert** [comment]
yes they will show up last.
