### ISSUE TITLE
Netlify CMS Fixes

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/sophiamcclennen.com#16]
- [x] Make `news` and `posts` (articles) produce files that match existing: `yyyy-mm-dd-slug`
- [ ] Fix broken image in entry screen (see below image)
- [x] Update fields for reviews: 
   - [x] Remove "link to original"
   - [x] Add Related book (of course, make sure actual relationship works)
- [ ] Make images show for book entries (in CMS landing)
- [x] Hide preview anywhere we don't have the actual nice preview (ask if you have questions. I'm referring to the preview icon in entries)

![Screen Shot 2021-05-19 at 12 18 13 PM](https://user-images.githubusercontent.com/115347/118848008-59723d00-b89c-11eb-8764-ca0d98651146.jpg)

**Comment by budparr** [comment]
![Screen Shot 2021-05-19 at 1 20 18 PM](https://user-images.githubusercontent.com/115347/118856482-fdf87d00-b8a4-11eb-9d93-0c9f32141408.jpg)

**Comment by budparr** [comment]
Hmm. Looks like the issue is in Safari. There is no image at all in Chrome

**Comment by regisphilibert** [comment]
> Make images show for book entries (in CMS landing)

Unfortunately there's no way to have HTML in the `summary` field for collections... It's pretty limited even with the [new string transformation](https://www.netlifycms.org/docs/beta-features/#summary-string-template-transformations)

**Comment by regisphilibert** [comment]
Also: https://github.com/netlify/netlify-cms/issues/5411

**Comment by regisphilibert** [comment]
@budparr I can merge what we have.

**Comment by budparr** [comment]
LGTM!

**Comment by budparr** [comment]
did you merge your changes? I'm not seeing a PR and I don't see the previews.
